#ifndef BULBA_CORE_RENDER_MODE_H
#define BULBA_CORE_RENDER_MODE_H

typedef enum {
  BLB_RENDER_OPAQUE = 0,
  BLB_RENDER_TRANSPARENT = 1,
  BLB_RENDER_ADDITIVE = 2,
  BLB_RENDER_MODE_COUNT = 3
} BLB_RenderMode;

#endif
